sudo: required
services:
  - docker

before_install:
  - docker build -t pklepikov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pklepikov/docker-react npm run test -- --coverage
