sudo: required
services:
  - docker

before_install:
  - docker build -t pklepikov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pklepikov/docker-react npm run test -- --coverage

# http://docker-env.eba-6fsm9tnp.us-east-1.elasticbeanstalk.com/
#deploy:
#  provider: elasticbeanstalk
#  region: "us-east-1"
#  app: "docker"
#  env: "Docker-env"
#  bucket_name: "elasticbeanstalk-us-east-1-087260325355"
#  bucket_path: "docker"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"